---
title: "Simulate Data"
output: html_document
---

# One causal factor

## No shift, same cor, same coef

```{r}
param.list.0 <- list(
  n.trial1 = 200, 
  n.trial2 = 800,
  n.causal = 1, coef.causal = 1,
  n.cor.causal = 5, cor.causal = .95,
  n.noise = 15, outcome.sd = 1,
  shift.mean = 0, shift.sd = .1,
  n.sim = 100)

param.list <- param.list.0

simu.1 <- sapply(1:param.list$n.sim, function(s){
  set.seed(s)
  simu.out <- simu(n.trial1 =  param.list$n.trial1, n.trial2 = param.list$n.trial2, 
                 n.causal = param.list$n.causal, n.cor.causal = param.list$n.cor.causal, 
                 cor.causal = param.list$cor.causal, coef.causal=param.list$coef.causal,
                 n.noise=param.list$n.noise, outcome.sd=param.list$outcome.sd,
                 shift.mean = param.list$shift.mean, shift.sd=param.list$shift.sd)
  
  }, simplify = F)

```

### Subset so that true causal is not


## No shift, different cor, same coef

```{r}
param.list <- param.list.0
param.list$cor.causal <- c(.95, .8)

simu.2 <- sapply(1:param.list$n.sim, function(s){
  set.seed(s)
  simu.out <- simu(n.trial1 =  param.list$n.trial1, n.trial2 = param.list$n.trial2, 
                 n.causal = param.list$n.causal, n.cor.causal = param.list$n.cor.causal, 
                 cor.causal = param.list$cor.causal, coef.causal=param.list$coef.causal,
                 n.noise=param.list$n.noise, outcome.sd=param.list$outcome.sd,
                 shift.mean = param.list$shift.mean, shift.sd=param.list$shift.sd)
  
  }, simplify = F)

```

## No shift, same cor, diff coef
```{r}
param.list <- param.list.0
param.list$coef.causal <- c(1, .8)

simu.3 <- sapply(1:param.list$n.sim, function(s){
  set.seed(s)
  simu.out <- simu(n.trial1 =  param.list$n.trial1, n.trial2 = param.list$n.trial2, 
                 n.causal = param.list$n.causal, n.cor.causal = param.list$n.cor.causal, 
                 cor.causal = param.list$cor.causal, coef.causal=param.list$coef.causal,
                 n.noise=param.list$n.noise, outcome.sd=param.list$outcome.sd,
                 shift.mean = param.list$shift.mean, shift.sd=param.list$shift.sd)
  
  }, simplify = F)

```


## With shift, same cor, same coef
```{r}
param.list <- param.list.0
param.list$shift.mean <- c(.05)

simu.4 <- sapply(1:param.list$n.sim, function(s){
  set.seed(s)
  simu.out <- simu(n.trial1 =  param.list$n.trial1, n.trial2 = param.list$n.trial2, 
                 n.causal = param.list$n.causal, n.cor.causal = param.list$n.cor.causal, 
                 cor.causal = param.list$cor.causal, coef.causal=param.list$coef.causal,
                 n.noise=param.list$n.noise, outcome.sd=param.list$outcome.sd,
                 shift.mean = param.list$shift.mean, shift.sd=param.list$shift.sd)
  
  }, simplify = F)

```

```{r}
save.image("simudata.rda")
```
