---
title: "Simulation Results"
author: "Ning Leng"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    number_sections: true
    fig_width: 12
    fig_height: 7
    code_folding: hide
geometry: margin=2cm
sansfont: Calibri Light
---

# Simulation structure
```{r, include=F, echo=F}
library(pensim)
library(tidyverse)
library(knitr)
library(glmnet)
library(pheatmap)
library(knitr)
source("util.R")
set.seed(10)

section.names <- c("No shift, same cor, same coef", "No shift, different cor, same coef", "No shift, same cor, diff coef", "With shift, same cor, same coef")
load("simudata.rda")



summary.cor <- function(simu.out){
  x.names <- simu.out$x.names[which(substr(simu.out$x.names,1,2)=="a.")]
  xcor.trial1 <- cor(simu.out$data %>% filter(trial=="trial1") %>% select(!!x.names, outcome))
  xcor.trial2 <- cor(simu.out$data %>% filter(trial=="trial2") %>% select(!!x.names, outcome))
  x.shift <- simu.out$data %>% group_by(trial) %>% summarize(a0_mean=mean(a.0))
  model.trial1 <- coef(summary(lm(outcome~a.0, data=simu.out$data %>% filter(trial=="trial1"))))
  model.trial2 <- coef(summary(lm(outcome~a.0, data=simu.out$data %>% filter(trial=="trial2"))))
  out <- list(xcor.trial1=xcor.trial1, xcor.trial2=xcor.trial2, x.shift=x.shift,
              model.trial1=model.trial1, model.trial2=model.trial2)
}

```





```{r, message=FALSE, warning=FALSE, results="asis"}
for(i in 1:4){
  cat(paste0("## Heatmap: Simu ", i, ":", section.names[i],"\n\n\n"))
  simutmp <- get(paste0("simu.",i))
  heat.fun(simutmp[[1]])
  #print(summary.cor(simutmp[[1]]))
}
```




```{r}
for(i in 1:4){
  cat(paste0("## Statistics: Simu ", i, ":", section.names[i],"\n\n\n"))
  simutmp <- get(paste0("simu.",i))
  print(summary.cor(simutmp[[1]]))
}
```

# Analysis, all x observed



```{r, message=FALSE, warning=FALSE, results="asis"}
for(i in 1:4){
  cat(paste0("## Simu ", i, ":", section.names[i],"\n\n\n"))
  for(obs.subset in c(TRUE)){
    suffix <- ifelse(obs.subset,"","noa0")
    simuname.out <- paste0("simu.",i, suffix)
    cat(paste0("Causal feacture observed? ", obs.subset, '\n\n\n'))

    cat("### Top selected features \n\n\n")
    res.v <- readRDS(paste0(simuname.out, ".res.v.rds"))
    lasso.top <- sapply(res.v, function(i)i$lasso.top.names[1])
    print(table(lasso.top))
    cat("\n\n\n")

    uni.top <- sapply(res.v, function(i)i$uni.top.names[1])
    print(table(uni.top))
    cat("\n\n\n")
    cat("### MSE \n\n\n")
    mse.plot.df <- readRDS(paste0(simuname.out,".mse.plot.df.rds"))
    mse.tab <- mse.plot.df %>% group_by(model, method) %>% summarise(mean=mean(mse), median=median(mse))
    print(kable(mse.tab))
    cat("\n\n\n")

  }
}


```


# Analysis, a.0 (causal) not observed



```{r, message=FALSE, warning=FALSE, results="asis"}
for(i in 1:4){
  cat(paste0("## Simu ", i, ":", section.names[i],"\n\n\n"))
  for(obs.subset in c(FALSE)){
    suffix <- ifelse(obs.subset,"","noa0")
    simuname.out <- paste0("simu.",i, suffix)
    cat(paste0("Causal feacture observed? ", obs.subset, '\n\n\n'))

    cat("### Top selected features \n\n\n")
    res.v <- readRDS(paste0(simuname.out, ".res.v.rds"))
    lasso.top <- sapply(res.v, function(i)i$lasso.top.names[1])
    print(table(lasso.top))
    cat("\n\n\n")
    uni.top <- sapply(res.v, function(i)i$uni.top.names[1])
    print(table(uni.top))
    cat("\n\n\n")
    cat("### MSE \n\n\n")
    mse.plot.df <- readRDS(paste0(simuname.out,".mse.plot.df.rds"))
    mse.tab <- mse.plot.df %>% group_by(model, method) %>% summarise(mean=mean(mse), median=median(mse))
    print(kable(mse.tab))
        cat("\n\n\n")

  }
}


```
